### ISSUE TITLE
jshell can't see dependencies

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#992]
with 

```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS https://github.com/blocoio/faker/tree/1.2.8

import io.bloco.faker.Faker;

Faker fake = new Faker("da-DK");
IntStream.range(0, 10).forEach(
           i-> System.out.println(fake.name.name())
        );
```

I get

```java
 jbang --verbose test.jsh
[jbang] jbang version 0.79.0
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] System Java version matches requested version 11
[jbang] run: /Users/max/.sdkman/candidates/java/current/bin/jshell --class-path=/Users/max/.m2/repository/com/github/blocoio/faker/1.2.8/faker-1.2.8.jar:/Users/max/.m2/repository/com/github/bmoliveira/snake-yaml/v1.18-android/snake-yaml-v1.18-android.jar:/Users/max/.m2/repository/joda-time/joda-time/2.9.1/joda-time-2.9.1.jar --startup=DEFAULT --startup=/var/folders/yb/sytszfld4sg8vwr1h0w20jlw0000gn/T/jbang_arguments_15400451799524567493test.jsh /Users/max/code/personal/test.jsh /var/folders/yb/sytszfld4sg8vwr1h0w20jlw0000gn/T/jbang_exit_8285782591836528220test.jsh
Error:
cannot find symbol
  symbol:   class Fake
import io.bloco.faker.Fake;
       ^-----------------^
Error:
cannot find symbol
  symbol:   class Faker
Faker fake = new Faker("da-DK");
^---^
Error:
cannot find symbol
  symbol:   class Faker
Faker fake = new Faker("da-DK");
                 ^---^
Error:
package fake does not exist
           i-> System.out.println(fake.name.name())
                                  ^-------^
```

which is weird since this works:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
// //DEPS <dependency1> <dependency2>
//DEPS https://github.com/blocoio/faker/tree/1.2.8

import static java.lang.System.*;

import java.util.stream.IntStream;

import io.bloco.faker.*;

public class test {

    public static void main(String... args) {
        Faker fake = new Faker("da-DK");
        IntStream.range(0, 10).forEach(
           i-> out.println(fake.name.name())
        );
    }
}
```

**Comment by tadayosi** [comment]
I think I hit the same issue. Today I found that what used to work before no longer works saying `java.lang.NoClassDefFoundError`:
https://github.com/tadayosi/jbang-sandbox/blob/main/camel/camel-app.jsh

**Comment by maxandersen** [comment]
Hmm. Any chance you know which jbang version it did work for you? I've tried locate which jdk / jshell doesn't work but no luck finding why.

**Comment by tadayosi** [comment]
So it's the latest `v0.88.0` (so it might not be the same issue as the original one...):
```
$ ./jbang-0.87.0/bin/jbang https://raw.githubusercontent.com/tadayosi/jbang-sandbox/main/camel/camel.jsh
Running Camel route...
Hello Camel!
Hello Camel!
Hello Camel!
```
```
$ ./jbang-0.88.0/bin/jbang https://raw.githubusercontent.com/tadayosi/jbang-sandbox/main/camel/camel.jsh
Running Camel route...
Exception java.lang.NoClassDefFoundError: org/apache/camel/main/Main
      at (#8:1)
Caused by: java.lang.ClassNotFoundException: org.apache.camel.main.Main
      at URLClassLoader.findClass (URLClassLoader.java:476)
      at DefaultLoaderDelegate$RemoteClassLoader.findClass (DefaultLoaderDelegate.java:154)
      at ClassLoader.loadClass (ClassLoader.java:589)
      at ClassLoader.loadClass (ClassLoader.java:522)
      ...
Exception java.lang.NoClassDefFoundError: org/apache/camel/main/Main
      at (#10:1)
Caused by: java.lang.ClassNotFoundException: org.apache.camel.main.Main
      at URLClassLoader.findClass (URLClassLoader.java:476)
      at DefaultLoaderDelegate$RemoteClassLoader.findClass (DefaultLoaderDelegate.java:154)
      at ClassLoader.loadClass (ClassLoader.java:589)
      at ClassLoader.loadClass (ClassLoader.java:522)
```

**Comment by tadayosi** [comment]
Ah by the way, looking at your original description:
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS https://github.com/blocoio/faker/tree/1.2.8

import io.bloco.faker.Fake;

Faker fake = new Faker("da-DK");
IntStream.range(0, 10).forEach(
           i-> System.out.println(fake.name.name())
        );
```
I found that this `import io.bloco.faker.Fake;` really should be `import io.bloco.faker.Faker;` (note the ending `-r`).

**Comment by tadayosi** [comment]
But again, even the fixed `test.jsh` doesn't run with `v0.88.0`:
```
$ cat test.jsh 
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS https://github.com/blocoio/faker/tree/1.2.8

import io.bloco.faker.Faker;

Faker fake = new Faker("da-DK");
IntStream.range(0, 10).forEach(
           i-> System.out.println(fake.name.name())
        );
```
```
$ ./jbang-0.88.0/bin/jbang test.jsh 
Exception java.lang.NoClassDefFoundError: io/bloco/faker/Faker
      at (#2:1)
Caused by: java.lang.ClassNotFoundException: io.bloco.faker.Faker
      at URLClassLoader.findClass (URLClassLoader.java:476)
      at DefaultLoaderDelegate$RemoteClassLoader.findClass (DefaultLoaderDelegate.java:154)
      at ClassLoader.loadClass (ClassLoader.java:589)
      at ClassLoader.loadClass (ClassLoader.java:522)
      ...
Exception java.lang.NoClassDefFoundError: io/bloco/faker/Faker
      at lambda$do_it$$0 (#3:2)
      at Streams$RangeIntSpliterator.forEachRemaining (Streams.java:104)
      at IntPipeline$Head.forEach (IntPipeline.java:593)
      at (#3:1)
Caused by: java.lang.ClassNotFoundException: io.bloco.faker.Faker
      at URLClassLoader.findClass (URLClassLoader.java:476)
      at DefaultLoaderDelegate$RemoteClassLoader.findClass (DefaultLoaderDelegate.java:154)
      at ClassLoader.loadClass (ClassLoader.java:589)
      at ClassLoader.loadClass (ClassLoader.java:522)
      ...
```
it works with `v0.87.0`.

**Comment by maxandersen** [comment]
@quintesse could this be caused by local exec ?

**Comment by quintesse** [comment]
Yes, that seems to be the culprit.... that sucks, it means we can forget about using JBang for stdin filters :-(
